version: "3.3"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    networks:
      - network
    volumes:
      - database:/var/lib/postgresql/data
  
  calcucator:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge
    
volumes:
  database:  